# Generated by Django 6.0.7 on 2026-07-09 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuwo_artist_id', models.CharField(max_length=50, unique=True, verbose_name='酷我歌手ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='歌手名')),
                ('artist_image', models.URLField(blank=True, max_length=500, verbose_name='歌手图片')),
                ('artist_intro', models.TextField(verbose_name='歌手简介')),
                ('artist_url', models.URLField(blank=True, max_length=500, verbose_name='歌手原始URL')),
                ('birthday', models.CharField(default='暂无信息', max_length=100, verbose_name='生日')),
                ('country', models.CharField(default='暂无信息', max_length=100, verbose_name='国家/地区')),
                ('music_num', models.PositiveIntegerField(default=0, verbose_name='歌曲数量')),
                ('album_num', models.PositiveIntegerField(default=0, verbose_name='专辑数量')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'ordering': ['artist_name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_order', models.PositiveIntegerField(default=0, verbose_name='歌曲序号')),
                ('kuwo_song_id', models.CharField(max_length=50, unique=True, verbose_name='酷我歌曲ID')),
                ('musicrid', models.CharField(blank=True, max_length=100, verbose_name='MusicRID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名')),
                ('artist_name', models.CharField(max_length=200, verbose_name='歌手名')),
                ('keyword', models.CharField(blank=True, max_length=100, verbose_name='搜索关键词')),
                ('album', models.CharField(default='无专辑归属', max_length=200, verbose_name='专辑')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='时长（秒）')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='歌曲封面')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='歌曲原始URL')),
                ('lyrics', models.TextField(verbose_name='歌词')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.artist', verbose_name='关联歌手')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['song_order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='匿名用户', max_length=50, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song', verbose_name='所属歌曲')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
